"""add phone column for user

Revision ID: 7446ca755e8f
Revises: 0737f7ac18c1
Create Date: 2026-09-04 20:59:45.358907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7446ca755e8f'
down_revision = '0737f7ac18c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
